driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/aptible-toolbelt']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24

platforms:
  - name: centos-7.2
    run_list: yum-epel::default
  - name: debian-8.4
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/aptible-toolbelt
