sudo: true
language: ruby
install: true
matrix:
  include:
    - os: osx
      osx_image: xcode8
      rvm: 2.2.4
      env:
        - BUILD_ENGINE=native
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=ubuntu-1404
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=ubuntu-1604
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=debian-7
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=debian-8
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=centos-6
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=centos-7
      services:
        - docker
before_install:
  - buildscripts/travis-pre-build.sh
script:
  - rm -f pkg/*
  - "buildscripts/${BUILD_ENGINE}.sh"
  - mkdir -p "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/"
  - sudo chown -R "$USER" pkg
  - mv pkg "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/pkg"
  - ls -lah "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/pkg"
deploy:
  skip_cleanup: true
  provider: s3
  bucket: omnibus-aptible-toolbelt
  acl: public_read
  local_dir: deploy
  access_key_id:
    secure: "pzuCxJwsM35hrw9n3rdZSiQlgOBAM2eQ0DwXxqGI5K8lCImuuZc8SsQZhrZacVB5NbL400CSE4GLwS/+53QR8AH15jT5IQQUyAx3qAk2wkc+FAdlRhsA+2/W6IhkYbAxI08sOgNqDuBIvSqr7vcJWzFnzgwc0ty531xnrsJKElXYIyvrETaqY2XF2s4IjCzHjzuSCSgjN8pP/c1jDpr4+t4N13LVl1N+5FivQDOSOphuGdFaPPq0Jmxq11anxG/RAH2Ju3xC4A5doiqWrGIxadtUz5zy8HADk3a30Lkf1rqOoGKrYUWAwttsJ+ervtXaYalpfz2pmbmNBJ4kZKzFhGxET3+vPF4YaupFV6SEo+JJ95XLekbfVGXfCs9Z0BhO0G8ZJTsnMxISJHyVt8q2IY0wRLtuzYLMW9sQZxe/cHxTiM3CP5bWIe+wIHhdLE2YBI8jkUc7/HhwesnN2d7gCHoJi2Ed8dV3dliygLzRkw7iTNxrfCibMG7ZdjOg5AyaFJV2pNB4vec3AMXzfFTipjTOMgTaewr7gmdLEIK705FkJWTMxtwiV9+UFo6Cm9yPVs6pFoR75AyeUcPTdxzOoa5QKHBQucZY659YxhFk7RyRAHUEVpdT40b+MSeYxG83cxZMK3VeJSBQ/gQaE1Pe1eGWSRhz8PU7Dc/9pGNTsjo="
  secret_access_key:
    secure: "dCfZn2XYm1RmFtkA5I2yjFiJT9EpuPBv3B0mPHML+Xe3JYbE2ZerRrsuVty4Jmu75r9NMdh5nCF++BwM+Eo5/ZKV7UvVqLGcdV5CpL53C4tgzFoP70pcwRRoZpAfLw13Uial8lvXAaReWh/x8aqr5wkw+t9bcmBTyn33cPM6mgizJllpq890HHvHmZV3IAriO0xcTiE2bnC8g2NR/j34d5P8mPWtb+dFBP1A0ZjCUMTn54z+T6+Ke7436BdfcEF+n3Mxlc6WPdXdgIuF/k5CAfoBto+GWwNI+I5+Ki/XQf8auQ/ibQLa27zcMIu5/kf4UfUtkINgF6l4GEXZ9cH5vJGvDvdvbKtqcWmBCilkBhoaTvN778l+8a0zwCKiONl8gWJeT9xu4u7w6sELABljF36YiFje3Wu58Lb3QMLughkGLRxUr9i0AhQaT/VfizmeZpUAQn4/NpCfHOnox7/sa2qlo+0btefGQleDNtkxkfGg2Ui5pz4bDMDtzxyxDOSLDjXI1+8xv0ghja9xJCZifVouUJEpxP9+564kEhu4l14nTk8dzoJx3Nrx9xnFVddsHd8Sb4RwYSaEjTbOQKpsRRsaIbrYyrLjoL/JUjfNUcTT4OcxC9dVYkafuY41y9Qc81QkrryW1lDpBJKGd7aHWgkToXLc5Hg9X8gPnxXDwPE="
  on:
    repo: aptible/omnibus-aptible-toolbelt
    all_branches: true
